// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminSetScopeReducer from "../admin_set_scope_reducer";
import AdminUpdateConfigReducer from "../admin_update_config_reducer";
import CreateOrUpdateQuestReducer from "../create_or_update_quest_reducer";
import DebugLinkSelfReducer from "../debug_link_self_reducer";
import DismissQuestReducer from "../dismiss_quest_reducer";
import GrantRoleReducer from "../grant_role_reducer";
import IngestCallStatsReducer from "../ingest_call_stats_reducer";
import IngestChannelMessageEventReducer from "../ingest_channel_message_event_reducer";
import IngestPresenceReducer from "../ingest_presence_reducer";
import LinkIdentityReducer from "../link_identity_reducer";
import MovePlayerReducer from "../move_player_reducer";
import PlaceDecorationReducer from "../place_decoration_reducer";
import RemoveDecorationReducer from "../remove_decoration_reducer";
import SetEmoteReducer from "../set_emote_reducer";
import SetGraphCursorReducer from "../set_graph_cursor_reducer";
import SetPersonalOptInReducer from "../set_personal_opt_in_reducer";
import SyncChannelMembershipReducer from "../sync_channel_membership_reducer";
import SyncTeamMembershipReducer from "../sync_team_membership_reducer";
import UpdateSubscriptionHealthReducer from "../update_subscription_health_reducer";
import UpsertBookingAppointmentReducer from "../upsert_booking_appointment_reducer";
import UpsertChannelReducer from "../upsert_channel_reducer";
import UpsertMeetingReducer from "../upsert_meeting_reducer";
import UpsertTeamReducer from "../upsert_team_reducer";
import UpsertUserReducer from "../upsert_user_reducer";

export type AdminSetScopeParams = __Infer<typeof AdminSetScopeReducer>;
export type AdminUpdateConfigParams = __Infer<typeof AdminUpdateConfigReducer>;
export type CreateOrUpdateQuestParams = __Infer<typeof CreateOrUpdateQuestReducer>;
export type DebugLinkSelfParams = __Infer<typeof DebugLinkSelfReducer>;
export type DismissQuestParams = __Infer<typeof DismissQuestReducer>;
export type GrantRoleParams = __Infer<typeof GrantRoleReducer>;
export type IngestCallStatsParams = __Infer<typeof IngestCallStatsReducer>;
export type IngestChannelMessageEventParams = __Infer<typeof IngestChannelMessageEventReducer>;
export type IngestPresenceParams = __Infer<typeof IngestPresenceReducer>;
export type LinkIdentityParams = __Infer<typeof LinkIdentityReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type PlaceDecorationParams = __Infer<typeof PlaceDecorationReducer>;
export type RemoveDecorationParams = __Infer<typeof RemoveDecorationReducer>;
export type SetEmoteParams = __Infer<typeof SetEmoteReducer>;
export type SetGraphCursorParams = __Infer<typeof SetGraphCursorReducer>;
export type SetPersonalOptInParams = __Infer<typeof SetPersonalOptInReducer>;
export type SyncChannelMembershipParams = __Infer<typeof SyncChannelMembershipReducer>;
export type SyncTeamMembershipParams = __Infer<typeof SyncTeamMembershipReducer>;
export type UpdateSubscriptionHealthParams = __Infer<typeof UpdateSubscriptionHealthReducer>;
export type UpsertBookingAppointmentParams = __Infer<typeof UpsertBookingAppointmentReducer>;
export type UpsertChannelParams = __Infer<typeof UpsertChannelReducer>;
export type UpsertMeetingParams = __Infer<typeof UpsertMeetingReducer>;
export type UpsertTeamParams = __Infer<typeof UpsertTeamReducer>;
export type UpsertUserParams = __Infer<typeof UpsertUserReducer>;

