// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  graphSubscriptionId: __t.string().primaryKey().name("graph_subscription_id"),
  resource: __t.string(),
  expiresAt: __t.u64().name("expires_at"),
  lastRenewedAt: __t.u64().name("last_renewed_at"),
  state: __t.string(),
});
