// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  appointmentId: __t.string().primaryKey().name("appointment_id"),
  businessId: __t.string().name("business_id"),
  serviceName: __t.string().name("service_name"),
  startsAt: __t.u64().name("starts_at"),
  status: __t.string(),
});
