// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  zoneId: __t.u32().name("zone_id"),
  ownerUserId: __t.string().name("owner_user_id"),
  propKind: __t.string().name("prop_kind"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rotation: __t.f32(),
  placedAt: __t.u64().name("placed_at"),
});
