// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdminSetScopeReducer from "./admin_set_scope_reducer";
import AdminUpdateConfigReducer from "./admin_update_config_reducer";
import CreateOrUpdateQuestReducer from "./create_or_update_quest_reducer";
import DebugLinkSelfReducer from "./debug_link_self_reducer";
import DismissQuestReducer from "./dismiss_quest_reducer";
import GrantRoleReducer from "./grant_role_reducer";
import IngestAuditStatsReducer from "./ingest_audit_stats_reducer";
import IngestCallStatsReducer from "./ingest_call_stats_reducer";
import IngestChannelMessageEventReducer from "./ingest_channel_message_event_reducer";
import IngestPresenceReducer from "./ingest_presence_reducer";
import LinkIdentityReducer from "./link_identity_reducer";
import MovePlayerReducer from "./move_player_reducer";
import PlaceDecorationReducer from "./place_decoration_reducer";
import RemoveDecorationReducer from "./remove_decoration_reducer";
import SetEmoteReducer from "./set_emote_reducer";
import SetGraphCursorReducer from "./set_graph_cursor_reducer";
import SetPersonalOptInReducer from "./set_personal_opt_in_reducer";
import SyncChannelMembershipReducer from "./sync_channel_membership_reducer";
import SyncTeamMembershipReducer from "./sync_team_membership_reducer";
import UpdateSubscriptionHealthReducer from "./update_subscription_health_reducer";
import UpsertBookingAppointmentReducer from "./upsert_booking_appointment_reducer";
import UpsertChannelReducer from "./upsert_channel_reducer";
import UpsertMeetingReducer from "./upsert_meeting_reducer";
import UpsertTeamReducer from "./upsert_team_reducer";
import UpsertUserReducer from "./upsert_user_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AchievementRow from "./achievement_table";
import AdminAuditRow from "./admin_audit_table";
import AdminAuditStatsRow from "./admin_audit_stats_table";
import AdminConfigViewRow from "./admin_config_view_table";
import AdminHealthRow from "./admin_health_table";
import BookingsAppointmentRow from "./bookings_appointment_table";
import CallStatsAggRow from "./call_stats_agg_table";
import DecorationRow from "./decoration_table";
import EvtRoomBurstRow from "./evt_room_burst_table";
import MeetingPortalsRow from "./meeting_portals_table";
import MyPrivateRoomsRow from "./my_private_rooms_table";
import MyQuestsRow from "./my_quests_table";
import PlayerStateRow from "./player_state_table";
import PresencePublicRow from "./presence_public_table";
import RoomActivityRow from "./room_activity_table";
import UserRow from "./user_table";
import WorldPolicyRow from "./world_policy_table";
import WorldRoomsRow from "./world_rooms_table";
import WorldStateRow from "./world_state_table";
import WorldZonesRow from "./world_zones_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  achievement: __table({
    name: 'achievement',
    indexes: [
      { accessor: 'id', name: 'achievement_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'team_id', name: 'achievement_team_id_idx_btree', algorithm: 'btree', columns: [
        'teamId',
      ] },
    ],
    constraints: [
      { name: 'achievement_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AchievementRow),
  bookingsAppointment: __table({
    name: 'bookings_appointment',
    indexes: [
      { accessor: 'appointment_id', name: 'bookings_appointment_appointment_id_idx_btree', algorithm: 'btree', columns: [
        'appointmentId',
      ] },
      { accessor: 'starts_at', name: 'bookings_appointment_starts_at_idx_btree', algorithm: 'btree', columns: [
        'startsAt',
      ] },
    ],
    constraints: [
      { name: 'bookings_appointment_appointment_id_key', constraint: 'unique', columns: ['appointmentId'] },
    ],
  }, BookingsAppointmentRow),
  callStatsAgg: __table({
    name: 'call_stats_agg',
    indexes: [
      { accessor: 'bucket_start', name: 'call_stats_agg_bucket_start_idx_btree', algorithm: 'btree', columns: [
        'bucketStart',
      ] },
      { accessor: 'id', name: 'call_stats_agg_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_stats_agg_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallStatsAggRow),
  decoration: __table({
    name: 'decoration',
    indexes: [
      { accessor: 'id', name: 'decoration_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'owner_user_id', name: 'decoration_owner_user_id_idx_btree', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
      { accessor: 'zone_id', name: 'decoration_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'decoration_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DecorationRow),
  evtRoomBurst: __table({
    name: 'evt_room_burst',
    indexes: [
      { accessor: 'id', name: 'evt_room_burst_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'evt_room_burst_id_key', constraint: 'unique', columns: ['id'] },
    ],
    event: true,
  }, EvtRoomBurstRow),
  playerState: __table({
    name: 'player_state',
    indexes: [
      { accessor: 'identity', name: 'player_state_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'zone_id', name: 'player_state_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'player_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerStateRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'user_id', name: 'user_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserRow),
  worldState: __table({
    name: 'world_state',
    indexes: [
      { accessor: 'id', name: 'world_state_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldStateRow),
  adminAudit: __table({
    name: 'admin_audit',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminAuditRow),
  adminAuditStats: __table({
    name: 'admin_audit_stats',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminAuditStatsRow),
  adminConfigView: __table({
    name: 'admin_config',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminConfigViewRow),
  adminHealth: __table({
    name: 'admin_health',
    indexes: [
    ],
    constraints: [
    ],
  }, AdminHealthRow),
  meetingPortals: __table({
    name: 'meeting_portals',
    indexes: [
    ],
    constraints: [
    ],
  }, MeetingPortalsRow),
  myPrivateRooms: __table({
    name: 'my_private_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPrivateRoomsRow),
  myQuests: __table({
    name: 'my_quests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQuestsRow),
  presencePublic: __table({
    name: 'presence_public',
    indexes: [
    ],
    constraints: [
    ],
  }, PresencePublicRow),
  roomActivity: __table({
    name: 'room_activity',
    indexes: [
    ],
    constraints: [
    ],
  }, RoomActivityRow),
  worldPolicy: __table({
    name: 'world_policy',
    indexes: [
    ],
    constraints: [
    ],
  }, WorldPolicyRow),
  worldRooms: __table({
    name: 'world_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, WorldRoomsRow),
  worldZones: __table({
    name: 'world_zones',
    indexes: [
    ],
    constraints: [
    ],
  }, WorldZonesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("admin_set_scope", AdminSetScopeReducer),
  __reducerSchema("admin_update_config", AdminUpdateConfigReducer),
  __reducerSchema("create_or_update_quest", CreateOrUpdateQuestReducer),
  __reducerSchema("debug_link_self", DebugLinkSelfReducer),
  __reducerSchema("dismiss_quest", DismissQuestReducer),
  __reducerSchema("grant_role", GrantRoleReducer),
  __reducerSchema("ingest_audit_stats", IngestAuditStatsReducer),
  __reducerSchema("ingest_call_stats", IngestCallStatsReducer),
  __reducerSchema("ingest_channel_message_event", IngestChannelMessageEventReducer),
  __reducerSchema("ingest_presence", IngestPresenceReducer),
  __reducerSchema("link_identity", LinkIdentityReducer),
  __reducerSchema("move_player", MovePlayerReducer),
  __reducerSchema("place_decoration", PlaceDecorationReducer),
  __reducerSchema("remove_decoration", RemoveDecorationReducer),
  __reducerSchema("set_emote", SetEmoteReducer),
  __reducerSchema("set_graph_cursor", SetGraphCursorReducer),
  __reducerSchema("set_personal_opt_in", SetPersonalOptInReducer),
  __reducerSchema("sync_channel_membership", SyncChannelMembershipReducer),
  __reducerSchema("sync_team_membership", SyncTeamMembershipReducer),
  __reducerSchema("update_subscription_health", UpdateSubscriptionHealthReducer),
  __reducerSchema("upsert_booking_appointment", UpsertBookingAppointmentReducer),
  __reducerSchema("upsert_channel", UpsertChannelReducer),
  __reducerSchema("upsert_meeting", UpsertMeetingReducer),
  __reducerSchema("upsert_team", UpsertTeamReducer),
  __reducerSchema("upsert_user", UpsertUserReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

