// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventId: __t.string(),
  eventType: __t.string(),
  occurredAtMicros: __t.u64(),
  teamId: __t.string(),
  channelId: __t.string(),
  actorUserId: __t.option(__t.string()),
  messageId: __t.option(__t.string()),
  threadId: __t.option(__t.string()),
};
