// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fileId: __t.string().primaryKey().name("file_id"),
  teamId: __t.string().name("team_id"),
  name: __t.string(),
  webUrl: __t.string().name("web_url"),
  modifiedAt: __t.u64().name("modified_at"),
});
