// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  teamId: __t.string().name("team_id"),
  userId: __t.string().name("user_id"),
  action: __t.string(),
  requestedBy: __t.string().name("requested_by"),
  status: __t.string(),
  resultRef: __t.option(__t.string()).name("result_ref"),
  createdAt: __t.u64().name("created_at"),
});
