// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questId: __t.string().primaryKey().name("quest_id"),
  userId: __t.string().name("user_id"),
  kind: __t.string(),
  title: __t.string(),
  sourceRef: __t.string().name("source_ref"),
  deeplink: __t.string(),
  createdAt: __t.u64().name("created_at"),
  status: __t.string(),
});
