// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  taskId: __t.string().primaryKey().name("task_id"),
  teamId: __t.string().name("team_id"),
  planTitle: __t.string().name("plan_title"),
  title: __t.string(),
  bucket: __t.string(),
  percentComplete: __t.u32().name("percent_complete"),
  due: __t.option(__t.string()),
  updatedAt: __t.u64().name("updated_at"),
});
