// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  userId: __t.string().name("user_id"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  zoneId: __t.u32().name("zone_id"),
  animation: __t.string(),
  emote: __t.option(__t.string()),
  online: __t.bool(),
  updatedAt: __t.u64().name("updated_at"),
});
