// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channelId: __t.string().name("channel_id"),
  windowKey: __t.string().name("window_key"),
  windowStart: __t.u64().name("window_start"),
  msgCount: __t.u32().name("msg_count"),
  reactCount: __t.u32().name("react_count"),
  activeUserEstimate: __t.u32().name("active_user_estimate"),
});
