// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  displayName: __t.string().name("display_name"),
  zoneId: __t.u32().name("zone_id"),
  availability: __t.string(),
  isActivePlayer: __t.bool().name("is_active_player"),
});
