// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Achievement = __t.object("Achievement", {
  id: __t.u64(),
  teamId: __t.string(),
  kind: __t.string(),
  earnedAt: __t.u64(),
  windowRef: __t.string(),
});
export type Achievement = __Infer<typeof Achievement>;

export const ActivityEvent = __t.object("ActivityEvent", {
  eventId: __t.string(),
  eventType: __t.string(),
  occurredAt: __t.u64(),
  teamId: __t.string(),
  channelId: __t.string(),
  actorUserId: __t.option(__t.string()),
  messageId: __t.option(__t.string()),
  threadId: __t.option(__t.string()),
  ingestedAt: __t.u64(),
});
export type ActivityEvent = __Infer<typeof ActivityEvent>;

export const AdminAudit = __t.object("AdminAudit", {});
export type AdminAudit = __Infer<typeof AdminAudit>;

export const AdminAuditStats = __t.object("AdminAuditStats", {});
export type AdminAuditStats = __Infer<typeof AdminAuditStats>;

export const AdminConfigView = __t.object("AdminConfigView", {});
export type AdminConfigView = __Infer<typeof AdminConfigView>;

export const AdminHealth = __t.object("AdminHealth", {});
export type AdminHealth = __Infer<typeof AdminHealth>;

export const AggView = __t.object("AggView", {
  channelId: __t.string(),
  windowKey: __t.string(),
  windowStart: __t.u64(),
  msgCount: __t.u32(),
  reactCount: __t.u32(),
  activeUserEstimate: __t.u32(),
});
export type AggView = __Infer<typeof AggView>;

export const AuditLog = __t.object("AuditLog", {
  id: __t.u64(),
  actor: __t.string(),
  action: __t.string(),
  at: __t.u64(),
  detailsRedacted: __t.string(),
});
export type AuditLog = __Infer<typeof AuditLog>;

export const AuditStatsAgg = __t.object("AuditStatsAgg", {
  id: __t.u64(),
  bucketStart: __t.u64(),
  category: __t.string(),
  count: __t.u32(),
});
export type AuditStatsAgg = __Infer<typeof AuditStatsAgg>;

export const BookingsAppointment = __t.object("BookingsAppointment", {
  appointmentId: __t.string(),
  businessId: __t.string(),
  serviceName: __t.string(),
  startsAt: __t.u64(),
  status: __t.string(),
});
export type BookingsAppointment = __Infer<typeof BookingsAppointment>;

export const CallStatsAgg = __t.object("CallStatsAgg", {
  id: __t.u64(),
  bucketStart: __t.u64(),
  modality: __t.string(),
  callCount: __t.u32(),
  totalMinutes: __t.f32(),
});
export type CallStatsAgg = __Infer<typeof CallStatsAgg>;

export const Channel = __t.object("Channel", {
  channelId: __t.string(),
  teamId: __t.string(),
  name: __t.string(),
  roomId: __t.u32(),
  isEnabled: __t.bool(),
  visibility: __t.string(),
});
export type Channel = __Infer<typeof Channel>;

export const ChannelActivityAgg = __t.object("ChannelActivityAgg", {
  id: __t.u64(),
  channelId: __t.string(),
  windowKey: __t.string(),
  windowStart: __t.u64(),
  msgCount: __t.u32(),
  reactCount: __t.u32(),
  activeUserEstimate: __t.u32(),
});
export type ChannelActivityAgg = __Infer<typeof ChannelActivityAgg>;

export const ChannelMember = __t.object("ChannelMember", {
  id: __t.u64(),
  channelId: __t.string(),
  userId: __t.string(),
  role: __t.string(),
  syncedAt: __t.u64(),
});
export type ChannelMember = __Infer<typeof ChannelMember>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
  updatedAt: __t.u64(),
});
export type Config = __Infer<typeof Config>;

export const Decoration = __t.object("Decoration", {
  id: __t.u64(),
  zoneId: __t.u32(),
  ownerUserId: __t.string(),
  propKind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  rotation: __t.f32(),
  placedAt: __t.u64(),
});
export type Decoration = __Infer<typeof Decoration>;

export const EvtRoomBurst = __t.object("EvtRoomBurst", {
  id: __t.u64(),
  channelId: __t.string(),
  roomId: __t.u32(),
  kind: __t.string(),
  magnitude: __t.f32(),
});
export type EvtRoomBurst = __Infer<typeof EvtRoomBurst>;

export const GraphCursor = __t.object("GraphCursor", {
  resource: __t.string(),
  deltaLink: __t.string(),
  updatedAt: __t.u64(),
});
export type GraphCursor = __Infer<typeof GraphCursor>;

export const IdentityLink = __t.object("IdentityLink", {
  identity: __t.identity(),
  userId: __t.string(),
  linkedAt: __t.u64(),
});
export type IdentityLink = __Infer<typeof IdentityLink>;

export const Meeting = __t.object("Meeting", {
  eventId: __t.string(),
  teamId: __t.option(__t.string()),
  zoneId: __t.u32(),
  subjectRedacted: __t.string(),
  startsAt: __t.u64(),
  endsAt: __t.u64(),
  joinUrl: __t.option(__t.string()),
  state: __t.string(),
});
export type Meeting = __Infer<typeof Meeting>;

export const MeetingPortalView = __t.object("MeetingPortalView", {
  eventId: __t.string(),
  zoneId: __t.u32(),
  startsAt: __t.u64(),
  endsAt: __t.u64(),
  state: __t.string(),
});
export type MeetingPortalView = __Infer<typeof MeetingPortalView>;

export const MeetingPortals = __t.object("MeetingPortals", {});
export type MeetingPortals = __Infer<typeof MeetingPortals>;

export const MyPrivateRooms = __t.object("MyPrivateRooms", {});
export type MyPrivateRooms = __Infer<typeof MyPrivateRooms>;

export const MyQuests = __t.object("MyQuests", {});
export type MyQuests = __Infer<typeof MyQuests>;

export const PlayerState = __t.object("PlayerState", {
  identity: __t.identity(),
  userId: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  zoneId: __t.u32(),
  animation: __t.string(),
  emote: __t.option(__t.string()),
  online: __t.bool(),
  updatedAt: __t.u64(),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const PolicyView = __t.object("PolicyView", {
  allowPresence: __t.bool(),
  allowAggregates: __t.bool(),
  safeMode: __t.bool(),
  devMode: __t.bool(),
  layoutVersion: __t.u32(),
  presenceFeature: __t.bool(),
});
export type PolicyView = __Infer<typeof PolicyView>;

export const Presence = __t.object("Presence", {
  userId: __t.string(),
  availability: __t.string(),
  activity: __t.string(),
  source: __t.string(),
  lastUpdated: __t.u64(),
});
export type Presence = __Infer<typeof Presence>;

export const PresencePublic = __t.object("PresencePublic", {});
export type PresencePublic = __Infer<typeof PresencePublic>;

export const PresenceView = __t.object("PresenceView", {
  userId: __t.string(),
  availability: __t.string(),
  source: __t.string(),
});
export type PresenceView = __Infer<typeof PresenceView>;

export const Quest = __t.object("Quest", {
  questId: __t.string(),
  userId: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  sourceRef: __t.string(),
  deeplink: __t.string(),
  createdAt: __t.u64(),
  status: __t.string(),
});
export type Quest = __Infer<typeof Quest>;

export const RoleGrant = __t.object("RoleGrant", {
  identity: __t.identity(),
  role: __t.string(),
  grantedAt: __t.u64(),
});
export type RoleGrant = __Infer<typeof RoleGrant>;

export const RoomActivity = __t.object("RoomActivity", {});
export type RoomActivity = __Infer<typeof RoomActivity>;

export const RoomState = __t.object("RoomState", {
  channelId: __t.string(),
  roomId: __t.u32(),
  glow: __t.f32(),
  lastActivityAt: __t.u64(),
});
export type RoomState = __Infer<typeof RoomState>;

export const RoomView = __t.object("RoomView", {
  channelId: __t.string(),
  teamId: __t.string(),
  name: __t.string(),
  roomId: __t.u32(),
  glow: __t.f32(),
  lastActivityAt: __t.u64(),
  isPrivate: __t.bool(),
});
export type RoomView = __Infer<typeof RoomView>;

export const StaffPresence = __t.object("StaffPresence", {});
export type StaffPresence = __Infer<typeof StaffPresence>;

export const StaffPresenceView = __t.object("StaffPresenceView", {
  userId: __t.string(),
  displayName: __t.string(),
  zoneId: __t.u32(),
  availability: __t.string(),
  isActivePlayer: __t.bool(),
});
export type StaffPresenceView = __Infer<typeof StaffPresenceView>;

export const SubscriptionHealth = __t.object("SubscriptionHealth", {
  graphSubscriptionId: __t.string(),
  resource: __t.string(),
  expiresAt: __t.u64(),
  lastRenewedAt: __t.u64(),
  state: __t.string(),
});
export type SubscriptionHealth = __Infer<typeof SubscriptionHealth>;

export const Team = __t.object("Team", {
  teamId: __t.string(),
  name: __t.string(),
  zoneId: __t.u32(),
  isEnabled: __t.bool(),
});
export type Team = __Infer<typeof Team>;

export const TeamMember = __t.object("TeamMember", {
  id: __t.u64(),
  teamId: __t.string(),
  userId: __t.string(),
  role: __t.string(),
  syncedAt: __t.u64(),
});
export type TeamMember = __Infer<typeof TeamMember>;

export const TickAggTimer = __t.object("TickAggTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickAggTimer = __Infer<typeof TickAggTimer>;

export const TickAmbientTimer = __t.object("TickAmbientTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickAmbientTimer = __Infer<typeof TickAmbientTimer>;

export const TickGlowDecayTimer = __t.object("TickGlowDecayTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickGlowDecayTimer = __Infer<typeof TickGlowDecayTimer>;

export const TickRetentionTimer = __t.object("TickRetentionTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickRetentionTimer = __Infer<typeof TickRetentionTimer>;

export const User = __t.object("User", {
  userId: __t.string(),
  displayName: __t.string(),
  dept: __t.string(),
  title: __t.string(),
  avatarSeed: __t.u32(),
  optInPersonal: __t.bool(),
  isActive: __t.bool(),
});
export type User = __Infer<typeof User>;

export const WorldPolicy = __t.object("WorldPolicy", {});
export type WorldPolicy = __Infer<typeof WorldPolicy>;

export const WorldRooms = __t.object("WorldRooms", {});
export type WorldRooms = __Infer<typeof WorldRooms>;

export const WorldState = __t.object("WorldState", {
  id: __t.u32(),
  dayPhase: __t.f32(),
  mood: __t.f32(),
  updatedAt: __t.u64(),
});
export type WorldState = __Infer<typeof WorldState>;

export const WorldZones = __t.object("WorldZones", {});
export type WorldZones = __Infer<typeof WorldZones>;

export const ZoneView = __t.object("ZoneView", {
  teamId: __t.string(),
  name: __t.string(),
  zoneId: __t.u32(),
});
export type ZoneView = __Infer<typeof ZoneView>;

