// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventId: __t.string(),
  teamId: __t.option(__t.string()),
  zoneId: __t.u32(),
  subjectRedacted: __t.string(),
  startsAtMicros: __t.u64(),
  endsAtMicros: __t.u64(),
  joinUrl: __t.option(__t.string()),
};
