// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  displayName: __t.string().name("display_name"),
  dept: __t.string(),
  title: __t.string(),
  avatarSeed: __t.u32().name("avatar_seed"),
  optInPersonal: __t.bool().name("opt_in_personal"),
  isActive: __t.bool().name("is_active"),
});
