// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channelId: __t.string().name("channel_id"),
  teamId: __t.string().name("team_id"),
  name: __t.string(),
  roomId: __t.u32().name("room_id"),
  glow: __t.f32(),
  lastActivityAt: __t.u64().name("last_activity_at"),
  isPrivate: __t.bool().name("is_private"),
});
