// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  allowPresence: __t.bool().name("allow_presence"),
  allowAggregates: __t.bool().name("allow_aggregates"),
  allowContentOnClick: __t.bool().name("allow_content_on_click"),
  safeMode: __t.bool().name("safe_mode"),
  devMode: __t.bool().name("dev_mode"),
  layoutVersion: __t.u32().name("layout_version"),
  presenceFeature: __t.bool().name("presence_feature"),
});
