// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  teamId: __t.string().primaryKey().name("team_id"),
  fileCount: __t.u32().name("file_count"),
  recentCount7D: __t.u32().name("recent_count_7_d"),
  lastFileAt: __t.u64().name("last_file_at"),
});
